name: Playwright Tests

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Adjust based on your package manager

      - name: Run Playwright tests
        id: run-tests
        run: |
          npx playwright install  # Ensure Playwright is installed
          npm run test:add

  notify:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Test Result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_FREDDY }}
          SLACK_CHANNEL: "@freddy"
          SLACK_MESSAGE: "${{ needs.test.result == 'success' && '✅ Playwright Test Passed: Good' || '🚨 Playwright Test Failed: Bad' }}"
          SLACK_TITLE: "GitHub Action Test Result"
